#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

# Docker Compose for running the DSpace backend for e2e testing in a CI environment
# This is used by our GitHub CI at .github/workflows/build.yml
networks:
  dspacenet:
services:
  dspace:
    depends_on:
    - dspacedb
    image: dspace/dspace:dspace-7_x-test
    networks:
      dspacenet:
    ports:
    - published: 8080
      target: 8080
    stdin_open: true
    tty: true
    volumes:
    - assetstore:/dspace/assetstore
    - "./local.cfg:/dspace/config/local.cfg"
  dspacedb:
    environment:
      # This LOADSQL should be kept in sync with the LOADSQL in
      # https://github.com/DSpace/DSpace/blob/main/dspace/src/main/docker-compose/db.entities.yml
      LOADSQL: https://www.dropbox.com/s/4ap1y6deseoc8ws/dspace7-entities-2019-11-28.sql?dl=1
      PGDATA: /pgdata
    image: dspace/dspace-postgres-pgcrypto:loadsql
    networks:
      dspacenet:
    stdin_open: true
    tty: true
    volumes:
    - pgdata:/pgdata
  dspacesolr:
    image: dspace/dspace-solr
    networks:
      dspacenet:
    ports:
    - published: 8983
      target: 8983
    stdin_open: true
    tty: true
    volumes:
    - solr_authority:/opt/solr/server/solr/authority/data
    - solr_oai:/opt/solr/server/solr/oai/data
    - solr_search:/opt/solr/server/solr/search/data
    - solr_statistics:/opt/solr/server/solr/statistics/data
version: '3.7'
volumes:
  assetstore:
  pgdata:
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics:
