version: '3.7'
services:
  dspace-angular:
    environment:
      DSPACE_HOST: dspace-angular
      DSPACE_NAMESPACE: /
      DSPACE_PORT: '4000'
      DSPACE_SSL: "false"
    image: dspace/dspace-angular:latest
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
    - published: 4000
      target: 4000
    - published: 9876
      target: 9876
    stdin_open: true
    tty: true
    volumes:
        # tengo que crear un container para node_modules asi no me pisa los paquetes descargados en el build... Ver https://mherman.org/blog/dockerizing-an-angular-app/.
        -  /app/node_modules
        - ..:/app/
        - ./environment.dev.ts:/app/src/environments/environment.dev.ts
