version: '3.7'
networks:
  dspacenet:
services:
  dspace-angular:
    container_name: dspace-angular
    environment:
      DSPACE_HOST: dspace-angular
      DSPACE_NAMESPACE: /
      DSPACE_PORT: '3000'
      DSPACE_SSL: "false"
    image: dspace/dspace-angular:latest
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      dspacenet:
    ports:
    - published: 3000
      target: 3000
    - published: 9876
      target: 9876
    stdin_open: true
    tty: true
    volumes:
        # tengo que crear un container para node_modules asi no me pisa los paquetes descargados en el build... Ver https://mherman.org/blog/dockerizing-an-angular-app/.
        -  /app/node_modules
        - ..:/app/
        - ./environment.dev.js:/app/config/environment.dev.js
